# This startup helper is generated by install.ps1.
# It is also available as a template for reboot persistence.

$installDir = "$env:ProgramData\RemoteADBBack"
Start-Process -FilePath "$installDir\adb.exe" -ArgumentList 'start-server' -NoNewWindow -WindowStyle Hidden
Start-Sleep -Seconds 2
Start-Process -FilePath "$installDir\adb.exe" -ArgumentList 'reverse tcp:5200 tcp:5200' -NoNewWindow -WindowStyle Hidden
