#!/usr/bin/env bash
# RemoteADB — Linux / macOS backend installer
# Usage: bash install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"

echo "╔══════════════════════════════════════╗"
echo "║   RemoteADB Backend Installer        ║"
echo "╚══════════════════════════════════════╝"
echo "Backend: $BACKEND_DIR"
echo ""

# ── Node.js check ──────────────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  echo "❌ Node.js not found. Install from https://nodejs.org (v18+)"
  exit 1
fi
NODE_VER=$(node -e "process.stdout.write(process.version)")
echo "✅ Node.js $NODE_VER"

# ── ADB check ─────────────────────────────────────────────────────────────────
if command -v adb &>/dev/null; then
  ADB_VER=$(adb version | head -1)
  echo "✅ $ADB_VER"
  export ADB_PATH="$(which adb)"
else
  echo "⚠️  adb not found in PATH."
  echo "   Install Android Platform Tools:"
  echo "   https://developer.android.com/tools/releases/platform-tools"
fi

# ── npm install ────────────────────────────────────────────────────────────────
echo ""
echo "Installing Node.js dependencies..."
cd "$BACKEND_DIR"
npm install --production
echo "✅ Dependencies installed."

# ── start script ──────────────────────────────────────────────────────────────
START_SCRIPT="$BACKEND_DIR/start.sh"
cat > "$START_SCRIPT" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by install.sh
cd "$(dirname "$0")"
exec node src/backend.js "$@"
EOF
chmod +x "$START_SCRIPT"
echo "✅ Start script: $START_SCRIPT"

# ── systemd service (Linux only) ──────────────────────────────────────────────
if [[ "$(uname -s)" == "Linux" ]] && command -v systemctl &>/dev/null; then
  echo ""
  read -r -p "Install as systemd service (remoteadb)? [y/N] " REPLY
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    NODE_BIN="$(which node)"
    CURRENT_USER="$(whoami)"
    SERVICE_FILE="/etc/systemd/system/remoteadb.service"

    sudo tee "$SERVICE_FILE" > /dev/null <<UNIT
[Unit]
Description=RemoteADB Backend Server
After=network.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$BACKEND_DIR
ExecStart=$NODE_BIN src/backend.js
Restart=on-failure
RestartSec=5
Environment=PORT=5200

[Install]
WantedBy=multi-user.target
UNIT

    sudo systemctl daemon-reload
    sudo systemctl enable remoteadb
    sudo systemctl start remoteadb
    echo "✅ Service installed and started."
    echo "   Manage: sudo systemctl {start|stop|restart|status} remoteadb"
  fi
fi

# ── launchd plist (macOS only) ────────────────────────────────────────────────
if [[ "$(uname -s)" == "Darwin" ]]; then
  echo ""
  read -r -p "Install as launchd user agent (auto-start on login)? [y/N] " REPLY
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    NODE_BIN="$(which node)"
    PLIST_DIR="$HOME/Library/LaunchAgents"
    PLIST_FILE="$PLIST_DIR/com.remoteadb.backend.plist"
    mkdir -p "$PLIST_DIR"
    cat > "$PLIST_FILE" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.remoteadb.backend</string>
  <key>ProgramArguments</key>
  <array>
    <string>$NODE_BIN</string>
    <string>$BACKEND_DIR/src/backend.js</string>
  </array>
  <key>WorkingDirectory</key><string>$BACKEND_DIR</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>EnvironmentVariables</key>
  <dict><key>PORT</key><string>5200</string></dict>
  <key>StandardOutPath</key><string>/tmp/remoteadb.log</string>
  <key>StandardErrorPath</key><string>/tmp/remoteadb-err.log</string>
</dict>
</plist>
PLIST
    launchctl load "$PLIST_FILE"
    echo "✅ launchd agent installed."
    echo "   Manage: launchctl {load|unload} $PLIST_FILE"
  fi
fi

echo ""
echo "══════════════════════════════════════"
echo "  Installation complete!"
echo ""
echo "  Start: $START_SCRIPT"
echo "    or:  node $BACKEND_DIR/src/backend.js"
echo ""
echo "  Open:  http://localhost:5200"
echo "══════════════════════════════════════"
